### ISSUE TITLE
Keep the speed

### ISSUE THREAD

**Issue by racuna** [n0vella/cardo#2]
Hi, thanks for this app. Is a godsend for people who switch from mobile (Antennapod) to desktop and viceversa.

There is an issue about the new feature of the speed control. When a episode finishes, the next one plays at 1x even when the control keeps displaying 1.5x.

Something that also happens when I press play in another episode.

**Comment by n0vella** [comment]
https://github.com/n0vella/cardo/commit/b782f90290c6f6ca319bd3609522969c0bfc214b

**Comment by racuna** [comment]
Thank you very much :)
